services:
  - type: web
    name: laravel-backend
    env: php
    plan: free
    buildCommand: "composer install && php artisan config:cache && php artisan route:cache"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
    disk:
      name: data
      mountPath: /var/data
    buildFilter:
      paths: ["*"]
    autoDeploy: true
    staticPublishPath: public
